### ISSUE TITLE
Content stream not working when doing a normal startup of bbb-webrtc-sfu

### ISSUE THREAD

**Issue by mariogasparoni** [mconf/bbb-webrtc-sfu#135]
**Endpoint(s) description :** 
WebRTC users (firefox/chrome) and RTP Users

**Media format :** 
Video H.264

**version/hash:**
0063cd45fa7cceb743b6108c0e5d49b26e41dd72

**Problem description / Steps to reproduce:** 
The application needs to be initiated after room's creation to make the content stream to work properly. If initiated before room's creation (which is the normal startup), the content sharing do not work properly.

**Expected Behavior**:
Content stream should work properly when bbb-webrtc-sfu does a normal startup

**Comment by prlanzarin** [comment]
I think reverting this commit https://github.com/mconf/bbb-webrtc-sfu/commit/1ec81faa2bc44edcf84388eb9a0067581ea79a27#diff-a7ee2440c4be1d1320ce7ee2765727f9
should fix this issue.

As I mentioned before, there are a set of improvements that came with the 2.4.3 merge that should avoid the problem that commit was trying to fix. I suggest reverting it and trying it out.

**Comment by prlanzarin** [comment]
btw not really a fan of tethering in-memory state to BBB state if the state which we are referring to doesn't have a way to be queried on app restarts. That's the case for the screensharing state. Since there's no persistence, we should either avoid doing that or implement a pair of pubsup querying messages to akka-apps for the state we're anchoring the app to.

**Comment by mariogasparoni** [comment]
This commit is indeed far from ideal. The goal was to solve the problem without touching bbb's core, but since bbb was changed this become useless. I will try reverting it to see if it works

**Comment by mariogasparoni** [comment]
Reverting the mentioned commit solves the problem.
