### ISSUE TITLE
Content stream not being sent to RTP Users

### ISSUE THREAD

**Issue by mariogasparoni** [mconf/bbb-webrtc-sfu#170]
**Endpoint(s) description :** 
RTP Users calling 'join' with MCU flag

**Media format :** 
Verified with H.264 , but should also happens with VP8 users 

**version/hash:**
d3ab9ddd3181028891bcddb691a5be795b4c775f

**Problem description / Steps to reproduce:** 
Steps 
1. Join a room with WEB browser and share screen
2. Join the room with an RTP endpoint (SIP, for example). RTP endpoint won't receive content stream.

**Expected Behavior**:
Content stream should be sent to RTP endpoints.

**Comment by prlanzarin** [comment]
Addressed in #172, might revisit it later.
