### ISSUE TITLE
Screenshare extra media with incompatible type

### ISSUE THREAD

**Issue by germanocaumo** [mconf/bbb-webrtc-sfu#19]
The second media can't be connected to others, but it has "sendrecv" as video type.

**Comment by prlanzarin** [comment]
Won't fix in 2.4.0. Don't when I'll fix this tbh.

**Comment by prlanzarin** [comment]
The screensharing RTP bridge has been disabled by default (https://github.com/mconf/bbb-webrtc-sfu/commit/bdf57de5d6af9452d7c02fc87a233df0483fe7f3). There's only one source media now, and it works properly. This isn't an issue anymore.
