### ISSUE TITLE
Improve logging metadata

### ISSUE THREAD

**Issue by prlanzarin** [mconf/bbb-webrtc-sfu#27]
Review multi-line logs.
Add metadata to logs associating them to fields of interest for postprocessing.
 * Some fields of interest:
    - userId
    - meetingId

**Comment by pedrobmarin** [comment]
sfu build version

**Comment by lfzawacki** [comment]
Messages like "Pipeline has a total of 1 active elements" should print meetingId when possible. Think about all the messages and add the good good stuff

**Comment by prlanzarin** [comment]
Review the `level` metadata indication. Suggestion: rename it to `log_level_str` to make it clear that the level value is a `string` and also make things nicer for whoever tries to parse it.

**Comment by prlanzarin** [comment]
https://github.com/mconf/bbb-webrtc-sfu/issues/37

**Comment by prlanzarin** [comment]
Change the current log file to have a static name (`bbb-webrtc-sfu.log`) and, on rotation, rename it to the current date-suffixed structure.

**Comment by prlanzarin** [comment]
Removed the v2.5.x marker. This is a cross-release endeavor that will take who knows how long. Keep this open and refer every log refactor related PR to this.
